# Generated by Django 4.2.6 on 2024-01-13 19:26

from django.db import migrations, models
import django.db.models.deletion
import reference_images.models.reference_model
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0010_alter_images_image_and_more'),
        ('reference_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='image',
            field=models.ImageField(upload_to=reference_images.models.reference_model.content_file_name),
        ),
        migrations.CreateModel(
            name='MoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('image', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo_app.images')),
                ('reference_image', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_images.reference')),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_url', models.UUIDField(default=uuid.uuid4)),
                ('is_public', models.BooleanField(default=True)),
                ('mood_image', models.ManyToManyField(to='reference_images.moodimage')),
            ],
        ),
    ]
