# Generated by Django 6.0.3 on 2026-06-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_images', '0002_alter_reference_image_moodimage_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mood',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
