services:
  photo_db:
    extends:
      service: db
      file: ../docker_nginx_manager/docker-compose.yml


#    container_name: postgresdb
#    image: postgres:17.5
#    restart: 'no' #always
#    env_file:
#      - ../photo_project.env
#    ports:
#      - 5432:5432
#    volumes:
#      - postgres-data:/var/lib/postgresql/data

  web:
    container_name: django_photo_dev
    env_file:
      - ../photo_project.env
    build:
      context: ..
      dockerfile: docker_photo_dev/Dockerfile
#    command: python manage.py runserver 0.0.0.0:8000
    command: python manage.py runsslserver 0.0.0.0:8080

    volumes:
      - ../photo_project:/code
    ports:
      - 8080:8080
#    depends_on:
#      - db

networks:
  default:
    name: "my-app-net"
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.57.0/24
#    external: true

volumes:
  postgres-data:
