from django.urls import path
from .views import *
app_name = 'photo'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('add_image/<int:gallery_id>/', AddImageView.as_view(), name='add_image'),
    path('about/', AboutView.as_view(), name='about'),
    path('gallery_form/', GalleryFormView.as_view(), name='gallery_form'),
    path('gallery_form/<int:gallery_id>/', GalleryFormView.as_view(), name='gallery_form'),
    path('gallery_insert_view/<int:gallery_id>/', GalleryInsertView.as_view(), name='gallery_insert_view'),
    path('gallery_list/', GalleryListView.as_view(), name='gallery_list'),
    path('gallery_view/<int:gallery_id>/', GalleryView.as_view(), name='gallery_view'),
    path('image', ImageView.as_view(), name='image'),
    path('image/<int:image_id>/', ImageView.as_view(), name='image'),
    path('image_comment/<int:image_id>/', ImageCommentView.as_view(), name='image_comment'),
    path('image_get/<int:image_id>/', ImageGetView.as_view(), name='image_get'),
    path('image_update/<int:image_id>/', UpdateImageView.as_view(), name='image_update'),
    path('link_category/add/', LinkCategoryCreateView.as_view(), name='link_category-add'),
    path('link_category/<int:pk>/', LinkCategoryUpdateView.as_view(), name='link_category-update'),
    path('links_form/', LinksFormView.as_view(), name='links_form'),
    path('links_form/<int:link_id>/', LinksFormView.as_view(), name='links_form'),
    path('links_table/<int:user_id>/', LinksTableView.as_view(), name='links_table'),
    path('model_release/<int:release>/', ModelReleaseView.as_view(), name='model_release'),
    path('model_release/', ModelReleaseView.as_view(), name='model_release'),
    path('model_release_update/<int:release>/', ModelReleaseUpdateView.as_view(), name='model_release_update'),
    path('model_release_update/', ModelReleaseUpdateView.as_view(), name='model_release_update'),
    path('privacy/', PrivacyView.as_view(), name='privacy'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
    path('release_preview/', ReleaseTemplateView.as_view(), name='release_preview'),
    path('release_preview/<int:release_id>/', ReleaseTemplateView.as_view(), name='release_preview'),
    path('terms/', TermsView.as_view(), name='terms'),
    path('thumb/', ImageGetThumbView.as_view(), name='thumb'),
    path('thumb/<int:image_id>/', ImageGetThumbView.as_view(), name='thumb'),
]
