# Generated by Django 3.2.5 on 2022-05-13 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photo_app.fields.phone_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('first_name', models.CharField(default=None, max_length=100, null=True)),
                ('is_model', models.BooleanField(default=True)),
                ('last_name', models.CharField(default=None, max_length=100, null=True)),
                ('phone', photo_app.fields.phone_field.PhoneField(default=None, max_length=31, null=True)),
                ('score', models.IntegerField(default=3)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_app.contact')),
            ],
        ),
    ]
