version: "3.7"

services:
  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  db:
    container_name: postgres_photo
    image: postgres:latest
    restart: 'no' #always
    env_file:
      - project.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  photo:
    container_name: photo_django
    build:
      context: ..
      dockerfile: docker_photo_deploy/Dockerfile
    command: gunicorn photo_project.wsgi:application --bind 0.0.0.0:8080 --workers=4

    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - staticfiles:/home/app/web/staticfiles
      - media:/home/app/web/photo_app/media

  nginx:
    container_name: nginx

    image: nginx:mainline-alpine
    restart: 'no' #always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../nginx:/etc/nginx/conf.d
      - staticfiles:/app/static/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - photo

networks:
  default:
    name: my-app-net
#    external: true

volumes:
  media:
    name: photo-media
  postgres-data:
  staticfiles:
    name: photo-static
