# Generated by Django 3.2.5 on 2022-03-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0003_alter_gallery_display_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='display_image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display', to='photo_app.images'),
        ),
    ]
