# Generated by Django 3.2.5 on 2022-04-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0006_images_raw_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public'), ('authenticated', 'Authenticated'), ('private', 'Private')], default='private', max_length=40, null=True),
        ),
    ]
