# Generated by Django 3.2.5 on 2022-04-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0007_gallery_privacy_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='is_public',
        ),
    ]
