# Generated by Django 3.2.5 on 2022-04-23 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0008_remove_gallery_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('privacy_level', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=40, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_app.images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
