# Generated by Django 4.2.6 on 2024-01-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0011_talentcategory_talent_gallery_talent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_real_name',
            field=models.BooleanField(default=True),
        ),
    ]
