# Generated by Django 4.2.6 on 2024-01-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0012_user_use_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='carousel',
            field=models.BooleanField(default=False),
        ),
    ]
